---
- name: Install editors
  community.general.pacman:
    name: "{{ editors }}"
    state: present
  become: true
  tags:
    - editors

- name: Install editors from Arch User Repository
  ansible.builtin.script: ../../../aur/install-aur.sh {{ item }}
  with_items: "{{ editors_aur }}"
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur
    - editors_aur

- name: Setup default Git configuration
  git_config: name="{{ item.name }}" scope=global value="{{ item.value }}"
  with_items:
    - {name: user.name, value: "{{ user_git_name }}"}
    - {name: user.email, value: "{{ user_email }}"}
    - {name: core.editor, value: vim}
  become_user: "{{ user_name }}"
  become: true
  tags:
    - git
