---
- name: Install Cloud Tools from Arch User Repository
  ansible.builtin.script: ../../../aur/install-aur.sh {{ item }}
  loop: "{{ cloud_tools_aur }}"
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur
    - cloud
