---
- hosts: localhost
  roles:
  - { role: base,            tags: ['base'] }
  - { role: browsers,        tags: ['browsers'] }
  - { role: developer-tools, tags: ['dev-tools'] }
  - { role: editors,         tags: ['editors'] }
  - { role: media,           tags: ['media'] }
  - { role: gnome,           tags: ['gnome'] }
