---
- name: Configure a Manjaro OS (Arch Linux distribution) GNOME 3 desktop
  hosts: localhost
  roles:
  - { role: base,            tags: ['base'] }
  - { role: users,           tags: ['users', 'never'] }
  - { role: printers,        tags: ['printers'] }
  - { role: browsers,        tags: ['browsers'] }
  - { role: developer-tools, tags: ['dev-tools'] }
  - { role: cloud-tools,     tags: ['cloud-tools'] }
  - { role: editors,         tags: ['editors'] }
  - { role: media,           tags: ['media'] }
  - { role: multimedia,      tags: ['multimedia'] }
  - { role: audio-tools,     tags: ['audio-tools'] }
  - { role: comms,           tags: ['comms'] }
  - { role: gnome,           tags: ['gnome'] }
  - { role: security,        tags: ['security'] }
  - { role: virtualization,  tags: ['virtualization'] }
