---
galaxy_info:
  author: Paulo Monteiro
  description: Virtualization tools (VirtualBox, Vagrant) for Manjaro/Arch Linux
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
      versions:
        - all

  galaxy_tags:
    - manjaro
    - arch
    - virtualization
    - vagrant
    - virtualbox

dependencies:
  - role: base
