---
galaxy_info:
  author: Paulo Monteiro
  description: Cloud tools and CLI utilities for Manjaro/Arch Linux
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
      versions:
        - all

  galaxy_tags:
    - manjaro
    - arch
    - cloud
    - gcp
    - googlecloud

dependencies: []
