---
- name: Dash to Dock - Set dash max icon size
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size
    value: "64"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Set dots colour
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots-color
    value: "'#ffffff'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Set dots border colour
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots-border-color
    value: "'#ffffff'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Set background colour
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/background-color
    value: "'#ffffff'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Set transparency mode
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/transparency-mode
    value: "'FIXED'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Set running indicator style
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/running-indicator-style
    value: "'DOTS'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Set background opacity
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/background-opacity
    value: "0.22"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Set dock position
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/dock-position
    value: "'BOTTOM'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

# Enabled settings
- name: Dash to Dock - Enable custom background color
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/custom-background-color
    value: "true"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Enable custom-theme-shrink
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink
    value: "true"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Enable multi monitor
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/multi-monitor
    value: "true"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

# Disabled settings
- name: Dash to Dock - Disable fixed icon size
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/icon-size-fixed
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Disable unity-backlit-items
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/unity-backlit-items
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: "Dash to Dock - Disable custom theme "
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/apply-custom-theme
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Disable running indicator dominant color
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/running-indicator-dominant-color
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Disable straight corners
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/force-straight-corner
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Disable show apps at top
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/show-apps-at-top
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Disable extend height
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/extend-height
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock

- name: Dash to Dock - Disable dock fixed
  community.general.dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - dash-to-dock
