---
- name: Keyboard Shortcuts - System settings
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/control-center
    value: "['<Super>t']"
    state: present
  become_user: "{{ user_name }}"
  become: true

- name: Keyboard Shortcuts - Hide all normal windows
  dconf:
    key: /org/gnome/desktop/wm/keybindings/show-desktop
    value: "['<Primary><Alt>d']"
    state: present
  become_user: "{{ user_name }}"
  become: true

- name: Keyboard Shortcuts - Default Browser
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/www
    value: "['<Super>w']"
    state: present
  become_user: "{{ user_name }}"
  become: true

- name: Keyboard Shortcuts - Home
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/home
    value: "['<Super>e']"
    state: present
  become_user: "{{ user_name }}"
  become: true

- name: Keyboard Shortcuts - Calculator
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/calculator
    value: "['<Super>c']"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - keyboard-shortcuts

- name: Keyboard Shortcuts - Defining custom bindings
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - keyboard-shortcuts

- name: Keyboard Shortcuts - Terminator name
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name
    value: "'Launch Terminator'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - keyboard-shortcuts

- name: Keyboard Shortcuts - Terminator binding
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding
    value: "'<Primary><Alt>t'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - keyboard-shortcuts

- name: Keyboard Shortcuts - Terminator comand
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command
    value: "'/usr/bin/terminator'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - keyboard-shortcuts

- name: "Force alt + tab to switch only on current workspace"
  dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
    state: present
  become_user: '{{ user_name }}'
  become: true
  tags:
    - keyboard-shortcuts
