---
- name: Mouse - Locate pointer
  community.general.dconf:
    key: /org/gnome/settings-daemon/peripherals/mouse/locate-pointer
    value: "true"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - peripherals

- name: Touchpad - Enable natural scrolling
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
    value: "true"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - peripherals

- name: Touchpad - Disable edge scrolling
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/edge-scrolling-enabled
    value: "false"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - peripherals

- name: Touchpad - Enable two finger scrolling
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled
    value: "true"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - peripherals

- name: Touchpad - Disable while typing
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/disable-while-typing
    value: "true"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - peripherals
