---
- name: Screensaver - background
  community.general.dconf:
    key: /org/gnome/desktop/screensaver/picture-uri
    value: "'file:///usr/share/backgrounds/gnome/ColdWarm.jpg'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - screensaver

- name: Screensaver - background
  community.general.dconf:
    key: /org/gnome/desktop/screensaver/picture-options
    value: "'zoom'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - screensaver
