---
- name: Window titlebars - Button Layout
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "'close,minimize,maximize:appmenu'"
    state: present
  become_user: "{{ user_name }}"
  become: true
  tags:
    - windows
