---
- name: Docker - Add user to docker group {{ user_name }}
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: docker
    append: true
  become: true
  notify: restart os
  tags:
    - docker
    - development

- name: Docker - Enable and start the docker daemon
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
    masked: false
  become: true
  tags:
    - docker
    - development
