---
- name: Add 'GOPATH' to .zshrc
  ansible.builtin.lineinfile:
    dest: /home/{{ user_name }}/.zshrc
    regexp: GOPATH
    line: export GOPATH=$HOME/go
    owner: "{{ user_name }}"
    state: present
  notify: source .zshrc
  tags:
    - development
    - go
