---
- name: Install Developer Tools
  community.general.pacman:
    name: "{{ developer_stack }}"
    state: present
  become_user: root
  become: true
  tags:
    - dev-tools
    - development

- name: Configure Go
  ansible.builtin.import_tasks: go.yml

- name: Install Developer Tools from Arch User Repository
  ansible.builtin.script: ../../../aur/install-aur.sh {{ item }}
  loop: "{{ developer_stack_aur }}"
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - dev-tools-aur
    - development-aur
    - development
    - aur

- name: Install nvm
  ansible.builtin.import_tasks: nvm.yml

- name: Configure docker
  ansible.builtin.import_tasks: docker-config.yml

- name: Configure Emacs
  ansible.builtin.import_tasks: emacs-config.yml

- name: Configure Tesseract
  ansible.builtin.import_tasks: tesseract.yml
