---
- name: Install Developer Tools
  community.general.pacman:
    name: "{{ developer_stack }}"
    state: present
  become_user: root
  become: true
  tags:
    - dev-tools
    - development

- include: go.yml

- name: Install Developer Tools from Arch User Repository
  ansible.builtin.script: ../../../aur/install-aur.sh {{ item }}
  with_items: "{{ developer_stack_aur }}"
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - dev-tools-aur
    - development-aur
    - development
    - aur

- include: nvm.yml
- include: docker-config.yml
- include: emacs-config.yml
- include: tesseract.yml
