---
- name: Install media tools from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ media_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur


- name: Install media packages
  pacman:
    name: '{{ media }}'
    state: present
  become: yes
