---
- name: Create bash shell aliases
  ansible.builtin.lineinfile:
    dest: /home/{{ user_name }}/.bashrc
    regexp: "{{ item }}"
    insertafter: "alias more=less"
    line: "{{ item }}"
    owner: "{{ user_name }}"
    state: present
  loop: "{{ shell_aliases }}"
  become_user: "{{ user_name }}"
  become: true
  tags:
    - bash
