---
- name: Update cache and upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
    upgrade_extra_args: --noconfirm
  become: true
  tags:
    - pre

- name: Install Utils
  community.general.pacman:
    name: "{{ utils }}"
    state: present
  become: true
  tags:
    - utils
    - base

- name: Install Utils from Arch User Repository
  ansible.builtin.shell: |
    set -o pipefail
    pamac build -d --no-confirm {{ item }} | grep "is up to date"
    if [ $? != 0 ]; then
      pamac build --no-confirm {{ item }}
    fi
  loop: "{{ utils_aur }}"
  become: true
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  tags:
    - base
    - utils-aur
    - aur

- name: Configure NTP
  ansible.builtin.import_tasks: ntp.yml

- name: Configure PIP
  ansible.builtin.import_tasks: pip.yml

- name: Configure Bash
  ansible.builtin.import_tasks: bash.yml

- name: Configure Zsh
  ansible.builtin.import_tasks: zsh.yml

- name: Configure terminator
  ansible.builtin.import_tasks: terminator.yml

- name: Creates Workspace directory
  ansible.builtin.file:
    path: /home/{{ user_name }}/Workspace
    state: directory
    mode: "0755"
  become_user: "{{ user_name }}"
  become: true
