---
- name: Make sure the NTP service is running
  ansible.builtin.systemd:
    state: started
    name: ntpd
  become: true
  tags:
    - ntp

- name: Set timezone to Europe/London
  community.general.timezone:
    name: Europe/London
  become: true
  tags:
    - ntp
