---
- name: Creates terminator config directory
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config/terminator
    state: directory
    mode: "0764"
  become: true
  become_user: "{{ user_name }}"
  tags:
    - terminator

- name: Configure Terminator
  ansible.builtin.copy:
    src: files/terminator_config
    dest: /home/{{ user_name }}/.config/terminator/config
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
  become: true
  become_user: "{{ user_name }}"
  tags:
    - terminator
