---
galaxy_info:
  author: Paulo Monteiro
  description: Base system configuration for Manjaro/Arch Linux
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
      versions:
        - all

  galaxy_tags:
    - manjaro
    - arch
    - linux
    - base
    - system

dependencies: []
