---
- name: "Docker - Add {{ user_name }} to docker group"
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
  become: yes
  notify: "restart os"
  tags:
    - docker

- name: "Docker - Enable and start the docker daemon"
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no
  become: yes
  tags:
    - docker
    