---
- name: Get latest release of the Node Version Manager (nvm) repository
  github_release:
    user: nvm-sh
    repo: nvm
    action: latest_release
  register: nvm_latest_version
  tags:
    - nvm
    - dev-tools


- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_latest_version.tag }}/install.sh | zsh
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
    - nvm
    - dev-tools